@baseUrl = http://localhost:3000
@accessToken = {{authenticate.response.body.accessToken}}

### Login
# @name authenticate
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "guest@email.com",
  "password": "123456"
}


### ========= USERS =========


### Create
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Guest User",
  "email": "guest@email.com",
  "password": "123456"
}

### Find All
GET {{baseUrl}}/users
?limit=10
&offset=0
Authorization: Bearer {{accessToken}}

### Find One
GET {{baseUrl}}/users/9fda87be-a3d4-4c2a-8a3a-ac058e31a78c
Authorization: Bearer {{accessToken}}

### Update
PATCH  {{baseUrl}}/users/35f98b50-bbe5-400c-8799-e6c697d73d88
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Guest User",
  "password": "123456"
}

### Remove -> Soft Delete
DELETE   {{baseUrl}}/users/76887adf-a97d-47f7-97a5-79ab6b6203de
Authorization: Bearer {{accessToken}}

### Restore -> Restore from soft delete
PUT {{baseUrl}}/users/9fda87be-a3d4-4c2a-8a3a-ac058e31a78c
Authorization: Bearer {{accessToken}}


### ========= TASKS =========


### Create
POST {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Nova task"
}

### Find All
GET {{baseUrl}}/tasks
?limit=2
&offset=1
Authorization: Bearer {{accessToken}}

### Find One
GET {{baseUrl}}/tasks/0f357ac6-6bc8-4a25-a46f-4588d0c9f139
Authorization: Bearer {{accessToken}}

### Update
PATCH  {{baseUrl}}/tasks/cb06576f-ba7c-478c-9882-e7b5a29d280f
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Teste de task",
  "isCompleted": false
}

### Remove
DELETE   {{baseUrl}}/tasks/0f357ac6-6bc8-4a25-a46f-4588d0c9f139
Authorization: Bearer {{accessToken}}
