@baseUrl = http://localhost:3000
@accessToken = {{authenticate.response.body.accessToken}}
@refreshToken = {{authenticate.response.body.refreshToken}}

### Login
# @name authenticate
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "isadora@email.com",
  "password": "123456"
}

### Refresh Token
# @name reAuthenticate
POST {{baseUrl}}/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}


### ========= USERS =========


### Create
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Guest User",
  "email": "guest@email.com",
  "password": "123456"
}

### Find All
GET {{baseUrl}}/users
?limit=10
&offset=0
Authorization: Bearer {{accessToken}}

### Find One
GET {{baseUrl}}/users/e0c46cfd-1296-4d71-aa51-01a86fe23875
Authorization: Bearer {{accessToken}}

### Update
PATCH  {{baseUrl}}/users/e0c46cfd-1296-4d71-aa51-01a86fe23875
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Isadora",
  "password": "123456"
}

### Remove -> Soft Delete
DELETE   {{baseUrl}}/users/e0c46cfd-1296-4d71-aa51-01a86fe23875
Authorization: Bearer {{accessToken}}

### Restore -> Restore from soft delete
PUT {{baseUrl}}/users/9fda87be-a3d4-4c2a-8a3a-ac058e31a78c
Authorization: Bearer {{accessToken}}


### ========= TASKS =========


### Create
POST {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Nova task"
}

### Find All
GET {{baseUrl}}/tasks
?limit=2
&offset=1
Authorization: Bearer {{accessToken}}

### Find One
GET {{baseUrl}}/tasks/e6962821-741c-45ad-9484-4d4f6e99d445
Authorization: Bearer {{accessToken}}

### Update
PATCH  {{baseUrl}}/tasks/e6962821-741c-45ad-9484-4d4f6e99d445
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Teste de task",
  "isCompleted": false
}

### Remove
DELETE   {{baseUrl}}/tasks/0f357ac6-6bc8-4a25-a46f-4588d0c9f139
Authorization: Bearer {{accessToken}}
