@baseUrl = http://localhost:3000

### Create
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Nova task",
  "userId": "76887adf-a97d-47f7-97a5-79ab6b6203de"
}

### Find All
GET {{baseUrl}}/tasks
?limit=2
&offset=1

### Find One
GET {{baseUrl}}/tasks/60b5aae0-8cff-4929-962b-0c411ff94d91

### Update
PATCH  {{baseUrl}}/tasks/ee4e41b9-86c6-4874-ac3a-573262c34914
Content-Type: application/json

{
  "title": "Teste de task editado",
  "isCompleted": true
}

### Remove
DELETE   {{baseUrl}}/tasks/63642e6b-a94b-4d8e-a221-7b9283299034
