@baseUrl = http://localhost:3000

### Create
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Task 1",
  "isCompleted": false,
  "createdAt": "2025-05-13T02:48:44.120Z",
  "updatedAt": "2025-05-13T02:48:44.120Z"
}


### Read All
GET {{baseUrl}}/tasks
?limit=10
&offset=0

### Read One
GET {{baseUrl}}/tasks/3

### Update
PATCH  {{baseUrl}}/tasks/3
Content-Type: application/json

{
  "title": "Task edited",
  "isCompleted": true
}

### Delete
DELETE   {{baseUrl}}/tasks/1
