@baseUrl = http://localhost:3000

### Create
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Nova task"
}

### Read All
GET {{baseUrl}}/tasks
?limit=10
&offset=0

### Read One
GET {{baseUrl}}/tasks/63642e6b-a94b-4d8e-a221-7b9283299034

### Update
PATCH  {{baseUrl}}/tasks/5c0e6599-25bb-4db7-acdd-035907f39282
Content-Type: application/json

{
  "title": "Teste de task editado",
  "isCompleted": true
}

### Delete
DELETE   {{baseUrl}}/tasks/63642e6b-a94b-4d8e-a221-7b9283299034
